{% set name = "PyTurboJPEG" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e60f4c401eefa5eba8ad5184c6dd2c707b4b76b5a592e2ce64c4f7f05840b22e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2
    - pip
  run:
    - python >=2
    - numpy
    - libjpeg-turbo

test:
  requires:
    - requests

about:
  home: https://github.com/lilohuang/PyTurboJPEG/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper of libjpeg-turbo for decoding and encoding JPEG image.
  doc_url: https://github.com/lilohuang/PyTurboJPEG/
  dev_url: https://github.com/lilohuang/PyTurboJPEG/

extra:
  recipe-maintainers:
    - carlodri
