{% set name = "PyTurboJPEG" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80e7ff8b63b236d077a080135f38a34549e111a3251d1bf05973e0baa1c31b50

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2
    - pip
  run:
    - python >=2
    - numpy
    - libjpeg-turbo

test:
  requires:
    - requests

about:
  home: https://github.com/lilohuang/PyTurboJPEG/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper of libjpeg-turbo for decoding and encoding JPEG image.
  doc_url: https://github.com/lilohuang/PyTurboJPEG/
  dev_url: https://github.com/lilohuang/PyTurboJPEG/

extra:
  recipe-maintainers:
    - carlodri
