{% set name = "PyTurboJPEG" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e7a1672699d0cc53e5cf4bf9d3a0abc081dff6e5774752e26e7b842fb45c1428

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2
    - pip
  run:
    - python >=2
    - numpy
    - libjpeg-turbo

test:
  requires:
    - requests

about:
  home: https://github.com/lilohuang/PyTurboJPEG/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper of libjpeg-turbo for decoding and encoding JPEG image.
  doc_url: https://github.com/lilohuang/PyTurboJPEG/
  dev_url: https://github.com/lilohuang/PyTurboJPEG/

extra:
  recipe-maintainers:
    - carlodri
